config/routes.rb
Rails.application.routes.draw do
  resources :photo_images
  resources :photos, except: :index
  resources :users
  resources :tags
  resources :favorite_photos, only: [:create, :destroy]
  
  get 'sessions/new'
  root 'static#home'
  get '/submit', to: 'photos#new'

  get '/sign_up',  to: 'users#new'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/search', to: 'tags#search', as: 'search'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo_image.rb
class PhotoImage < ApplicationRecord
	mount_uploader :image, PictureUploader
	belongs_to :photo
end

app/controllers/photo_images_controller.rb
class PhotoImagesController < ApplicationController
  before_action :set_photo_image, only: [:show, :edit, :update, :destroy]

  # GET /photo_images
  # GET /photo_images.json
  def index
    @photo_images = PhotoImage.all
  end

  # GET /photo_images/1
  # GET /photo_images/1.json
  def show
  end

  # GET /photo_images/new
  def new
    @photo_image = PhotoImage.new
  end

  # GET /photo_images/1/edit
  def edit
  end

  # POST /photo_images
  # POST /photo_images.json
  def create
    @photo_image = PhotoImage.new(photo_image_params)

    respond_to do |format|
      if @photo_image.save
        format.html { redirect_to @photo_image, notice: 'Photo image was successfully created.' }
        format.json { render :show, status: :created, location: @photo_image }
      else
        format.html { render :new }
        format.json { render json: @photo_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photo_images/1
  # PATCH/PUT /photo_images/1.json
  def update
    respond_to do |format|
      if @photo_image.update(photo_image_params)
        format.html { redirect_to @photo_image, notice: 'Photo image was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo_image }
      else
        format.html { render :edit }
        format.json { render json: @photo_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photo_images/1
  # DELETE /photo_images/1.json
  def destroy
    @photo_image.destroy
    respond_to do |format|
      format.html { redirect_to photo_images_url, notice: 'Photo image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo_image
      @photo_image = PhotoImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_image_params
      params.require(:photo_image).permit(:photo_id, :image)
    end
end

app/helpers/photo_images_helper.rb
module PhotoImagesHelper
end

app/views/photo_images/_form.html.erb
<%= form_with(model: photo_image, local: true) do |form| %>
  <% if photo_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo_image.errors.count, "error") %> prohibited this photo_image from being saved:</h2>

      <ul>
      <% photo_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photo_images/edit.html.erb
<h1>Editing Photo Image</h1>

<%= render 'form', photo_image: @photo_image %>

<%= link_to 'Show', @photo_image %> |
<%= link_to 'Back', photo_images_path %>

app/views/photo_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photo Images</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photo_images.each do |photo_image| %>
      <tr>
        <td><%= link_to 'Show', photo_image %></td>
        <td><%= link_to 'Edit', edit_photo_image_path(photo_image) %></td>
        <td><%= link_to 'Destroy', photo_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo Image', new_photo_image_path %>

app/views/photo_images/new.html.erb
<h1>New Photo Image</h1>

<%= render 'form', photo_image: @photo_image %>

<%= link_to 'Back', photo_images_path %>

app/views/photo_images/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_photo_image_path(@photo_image) %> |
<%= link_to 'Back', photo_images_path %>