config/routes.rb
Rails.application.routes.draw do
  resources :photo_images
  resources :photos, except: :index
  resources :users
  resources :tags
  resources :favorite_photos, only: [:create, :destroy]
  
  get 'sessions/new'
  root 'static#home'
  get '/submit', to: 'photos#new'

  get '/sign_up',  to: 'users#new'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/search', to: 'tags#search', as: 'search'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :photos, through: :taggings

	searchkick match: :word_start, searchable: [:name]
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
    @tags = Tag.all
    @user = current_user
    @photos = Photo.order('created_at DESC')
    # @photos = Photo.paginate(page: params[:page], per_page: 10).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def search
    options = {
      fields: %w(name),
      misspellings: { below: 5 }
      # page: params[:page], 
      # per_page: 10
    }

    @tags = Tag.search(params[:text], options)
    if @tags.blank?
      redirect_to tags_path, flash:{notice: "Try to search for tags! Ex. \"City\",\"Beach\" "}
    else
      render :index
    end
  end
end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/tags/_searchresult.html.erb
tag_arr = []


<% @tags.each do |x| %>
	<% x.photos.each do |y| %>
		<% y.photo_images.each do |z| %>
			<%= image_tag z.image.photoset.url, data: { show: photo_path(x) } %>
		<% end %>
	<% end %>
<% end %>

app/views/tags/index.html.erb
<% if @tags[0].name == params[:text] %>
<div class="col col-lg-6 col-lg-offset-3">
	<h1>Photos with the tag: <strong><%= params[:text] %></strong></h1>
	
</div>
	<div class="photoset-grid-user" style="visibility: hidden;">
		<%= render partial: 'searchresult', locals: { photos: @photos }%>
<% else %>
	<div class="row">
		<div class="text-center">
			<h1>Bummer!</h1>
			<p>There are no photos with the tag <strong><%= params[:text] %></strong></p>	
			<strong><%= link_to "Submit one instead?", submit_path %></strong>
		</div>	
	</div>
<% end %>

app/views/tags/index.js.erb
$('.home').html("<%= escape_javascript(render :partial => 'searchresult', locals: {photos: @photos}) %>")