config/routes.rb
Rails.application.routes.draw do
  resources :photo_images
  resources :photos, except: :index
  resources :users
  resources :tags
  resources :favorite_photos, only: [:create, :destroy]
  
  get 'sessions/new'
  root 'static#home'
  get '/submit', to: 'photos#new'

  get '/sign_up',  to: 'users#new'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/search', to: 'tags#search', as: 'search'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
	belongs_to :user
	has_many :photo_images, dependent: :destroy
	has_many :taggings
	has_many :tags, through: :taggings

	validates :photo_images, :presence => true

	validate :photo_size_validation

	private

	def photo_size_validation
    	errors[:photo_images] << "should be more than 2MB" if photo_images.size < 2.megabytes
  	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:show, :new, :edit]
  before_action :correct_user, only: [:edit, :update]

  # GET /photos
  # GET /photos.json
  def index
    redirect_to 'static#home'
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @greet = ['A magnificent submission', 'Love this photo? It was uploaded']
    @photo = Photo.find(params[:id])

  end

  # GET /photos/new
  def new
    @photo = Photo.new
    @greeting = ["got something beautiful you'd like to share with the world?", "feeling good today? Spread the happiness one photo at a time!", "show the world some lovin'." ]
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = current_user.photos.new
    @greeting = ["got something beautiful you'd like to share with the world?", "feeling good today? Spread the happiness one photo at a time!", "show the world some lovin'." ]


    # @photo.photo_images = photo_params[:photo_images].map do |img|
    #   byebug
    #   PhotoImage.new(image: img)
    # end
    # @photo = Photo.new(photo_params)
    # @photo.user_id = current_user.id
    respond_to do |format|
      if @photo.save
        # params[:photo]['images'].each do |img|
        @photo_image = PhotoImage.create(image: params[:photo][:photo_images], photo_id: @photo.id)
        # @photo_image = @photo.photo_images.create()
    
        format.html { redirect_to edit_photo_path(@photo), notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    # creates tag objects for photos
    tag_array = tag_params['tags'].split(',').each do |x|
      x.strip!
    end
    tag_array.each do |x|     
      if Tag.find_by(name: x)
        @tag = Tag.find_by(name: x)
      else
        @tag = Tag.create(name: x)
      end
        Tagging.create(photo_id: @photo.id, tag_id: @tag.id)
    end

    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:photo_images, :all_tags)
    end

      # Confirms user is logged in
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def tag_params
      params.require(:photo).permit(:tags)
    end

    # Confirms correct user has access
    def correct_user
      @user = Photo.find(params[:id]).user
      if current_user != @user
        redirect_to(root_url) unless current_user?(@user)
        flash[:warning] = "Whoops! You don't own this photo, so you can't edit it. Enjoy the other ones!"
      end
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for @photo do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @photo.id == nil %>
    <div class="field">
      <%= form.file_field :photo_images %>
    </div>
  <% else %>
    <div class="field">
      <%= form.label :tags, 'Insert tags here!' %>
      <%= form.text_field :tags, placeholder: 'Tags are separated by a comma', value: '' %>
    </div>
  <% end %>
  <%# form.hidden_field :user_id, :value => current_user.id %>

  <div class="actions">
    <%= form.submit 'Submit Photo', class: 'btn btn-default btn-lg' %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<div class="container">
  <div class="col col-lg-8 col-lg-offset-2">
    <div class="row text-center">
			<h1>Add tags</h1>
			<p>You're almost done, <strong><%= current_user.name %></strong>!</p>
			<p>We just need you to tag your photos for easier public access.</p>

			<%= render 'form', photo: @photo %>
		</div>
	</div>
</div>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<div class="container">
  <div class="col col-lg-8 col-lg-offset-2">
    <div class="row text-center">
      <h1><strong>Submit a photo</strong></h1>
      <p>Hi <strong><%= current_user.name %></strong>, <%= @greeting.sample %></p>
    </div>
  </div>
  
  <div class="col col-lg-2 col-lg-offset-5">
    <div class="row text-center">
      <%= render 'form', photo: @photo %>
    </div>
  </div>
</div>

app/views/photos/show.html.erb
<div class="row">	
	<div class="text-center">
		<p><%= @greet.sample %> by <strong><%= link_to @photo.user.name, user_path(@photo.user.id) %></strong></p>
		<div class="cover-img" style="background-image: url(<%= @photo.photo_images[0].image %>)"></div>
		<p></p>
		<% if !@photo.tags.empty? %>
			<strong><p>Tags: </p></strong> 		 
			<% @photo.tags.each do |x| %>
			  <%= x.name %>
			<% end %>
		<% else %>
			<strong><p>This photo isn't tagged yet </p></strong> 
		<% end %>
	</div>
</div>

<div class="row">
	<div class="text-center">
		<br>
		<p><%= link_to 'Submit Another?', submit_path %></p>
	</dir>
</div>

<% if current_user.id == @photo.user.id %>
	<%= link_to 'Edit', edit_photo_path(@photo) %> |
<% end %>
<%= link_to 'Back', root_path %>